{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  # this name uniquely identifies the service
  # if you have multiple services you may need to append a suffix
  name: {{ .Release.Name }}
spec:
  selector:
    # this should match the deployment selector
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
{{ end }}
